# syntax=docker/dockerfile:1

FROM golang:1.26.5-alpine3.24

# go-sqlite3 uses cgo, so we need a C toolchain
RUN apk add --no-cache gcc=15.2.0-r5 musl-dev=1.2.6-r2 && \
  go install github.com/air-verse/air@v1.67.4

ENV CGO_ENABLED=1
ENV CGO_CFLAGS=-D_LARGEFILE64_SOURCE

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
