// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package db

import (
	"context"
)

const countPlanExists = `-- name: CountPlanExists :one
SELECT COUNT(*) FROM plans WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) CountPlanExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlanExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserExists = `-- name: CountUserExists :one
SELECT COUNT(*) FROM users WHERE id = ?
`

func (q *Queries) CountUserExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccess = `-- name: GetAccess :one
SELECT access_level, invited_at FROM plan_access WHERE plan_id = ? AND user_id = ?
`

type GetAccessParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	UserID string `db:"user_id" json:"user_id"`
}

type GetAccessRow struct {
	AccessLevel string `db:"access_level" json:"access_level"`
	InvitedAt   int64  `db:"invited_at" json:"invited_at"`
}

func (q *Queries) GetAccess(ctx context.Context, arg GetAccessParams) (GetAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getAccess, arg.PlanID, arg.UserID)
	var i GetAccessRow
	err := row.Scan(&i.AccessLevel, &i.InvitedAt)
	return i, err
}

const getPlanAccess = `-- name: GetPlanAccess :many
SELECT user_id, access_level, invited_at FROM plan_access WHERE plan_id = ?
`

type GetPlanAccessRow struct {
	UserID      string `db:"user_id" json:"user_id"`
	AccessLevel string `db:"access_level" json:"access_level"`
	InvitedAt   int64  `db:"invited_at" json:"invited_at"`
}

func (q *Queries) GetPlanAccess(ctx context.Context, planID string) ([]GetPlanAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlanAccess, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlanAccessRow{}
	for rows.Next() {
		var i GetPlanAccessRow
		if err := rows.Scan(&i.UserID, &i.AccessLevel, &i.InvitedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlansForUser = `-- name: GetPlansForUser :many
SELECT p.data
FROM plans p
JOIN plan_access pa ON p.id = pa.plan_id
WHERE pa.user_id = ? AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
`

func (q *Queries) GetPlansForUser(ctx context.Context, userID string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getPlansForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantAccess = `-- name: GrantAccess :exec
INSERT OR REPLACE INTO plan_access (plan_id, user_id, access_level, invited_at) VALUES (?, ?, ?, ?)
`

type GrantAccessParams struct {
	PlanID      string `db:"plan_id" json:"plan_id"`
	UserID      string `db:"user_id" json:"user_id"`
	AccessLevel string `db:"access_level" json:"access_level"`
	InvitedAt   int64  `db:"invited_at" json:"invited_at"`
}

func (q *Queries) GrantAccess(ctx context.Context, arg GrantAccessParams) error {
	_, err := q.db.ExecContext(ctx, grantAccess,
		arg.PlanID,
		arg.UserID,
		arg.AccessLevel,
		arg.InvitedAt,
	)
	return err
}
