// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: benefit.sql

package db

import (
	"context"
	"database/sql"
)

const createBenefitDraft = `-- name: CreateBenefitDraft :exec
INSERT INTO benefits (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateBenefitDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateBenefitDraft(ctx context.Context, arg CreateBenefitDraftParams) error {
	_, err := q.db.ExecContext(ctx, createBenefitDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBenefit = `-- name: DeleteBenefit :execrows
UPDATE benefits SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteBenefitParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteBenefit(ctx context.Context, arg DeleteBenefitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBenefit, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findBenefitDraft = `-- name: FindBenefitDraft :one
SELECT id, type, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM benefits
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindBenefitDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindBenefitDraftRow struct {
	ID            string  `db:"id" json:"id"`
	Type          string  `db:"type" json:"type"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindBenefitDraft(ctx context.Context, arg FindBenefitDraftParams) (FindBenefitDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findBenefitDraft, arg.PlanID, arg.Status)
	var i FindBenefitDraftRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getBenefit = `-- name: GetBenefit :one
SELECT id, type, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM benefits
WHERE id = ? AND deleted_at IS NULL
`

type GetBenefitRow struct {
	ID            string  `db:"id" json:"id"`
	Type          string  `db:"type" json:"type"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetBenefit(ctx context.Context, id string) (GetBenefitRow, error) {
	row := q.db.QueryRowContext(ctx, getBenefit, id)
	var i GetBenefitRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteBenefits = `-- name: ListCompleteBenefits :many
SELECT id, type, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM benefits
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteBenefitsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteBenefitsRow struct {
	ID            string  `db:"id" json:"id"`
	Type          string  `db:"type" json:"type"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteBenefits(ctx context.Context, arg ListCompleteBenefitsParams) ([]ListCompleteBenefitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteBenefits, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteBenefitsRow{}
	for rows.Next() {
		var i ListCompleteBenefitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MonthlyAmount,
			&i.GrowthYr2,
			&i.GrowthYr3,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxBenefitSortOrder = `-- name: MaxBenefitSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM benefits WHERE plan_id = ?
`

func (q *Queries) MaxBenefitSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxBenefitSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveBenefitStep = `-- name: SaveBenefitStep :execrows
UPDATE benefits
SET type = ?, monthly_amount = ?, growth_yr2 = ?, growth_yr3 = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveBenefitStepParams struct {
	Type          string  `db:"type" json:"type"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) SaveBenefitStep(ctx context.Context, arg SaveBenefitStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveBenefitStep,
		arg.Type,
		arg.MonthlyAmount,
		arg.GrowthYr2,
		arg.GrowthYr3,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
