// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capital_asset.sql

package db

import (
	"context"
	"database/sql"
)

const createCapitalAssetDraft = `-- name: CreateCapitalAssetDraft :exec
INSERT INTO capital_assets (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateCapitalAssetDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCapitalAssetDraft(ctx context.Context, arg CreateCapitalAssetDraftParams) error {
	_, err := q.db.ExecContext(ctx, createCapitalAssetDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCapitalAsset = `-- name: DeleteCapitalAsset :execrows
UPDATE capital_assets SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteCapitalAssetParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteCapitalAsset(ctx context.Context, arg DeleteCapitalAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCapitalAsset, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findCapitalAssetDraft = `-- name: FindCapitalAssetDraft :one
SELECT id, name, purchase_cost, useful_life_months, salvage_value, purchase_month_index, depreciation_method, status, current_step
FROM capital_assets
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindCapitalAssetDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindCapitalAssetDraftRow struct {
	ID                 string `db:"id" json:"id"`
	Name               string `db:"name" json:"name"`
	PurchaseCost       int64  `db:"purchase_cost" json:"purchase_cost"`
	UsefulLifeMonths   int64  `db:"useful_life_months" json:"useful_life_months"`
	SalvageValue       int64  `db:"salvage_value" json:"salvage_value"`
	PurchaseMonthIndex int64  `db:"purchase_month_index" json:"purchase_month_index"`
	DepreciationMethod string `db:"depreciation_method" json:"depreciation_method"`
	Status             string `db:"status" json:"status"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) FindCapitalAssetDraft(ctx context.Context, arg FindCapitalAssetDraftParams) (FindCapitalAssetDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findCapitalAssetDraft, arg.PlanID, arg.Status)
	var i FindCapitalAssetDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PurchaseCost,
		&i.UsefulLifeMonths,
		&i.SalvageValue,
		&i.PurchaseMonthIndex,
		&i.DepreciationMethod,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getCapitalAsset = `-- name: GetCapitalAsset :one
SELECT id, name, purchase_cost, useful_life_months, salvage_value, purchase_month_index, depreciation_method, status, current_step
FROM capital_assets
WHERE id = ? AND deleted_at IS NULL
`

type GetCapitalAssetRow struct {
	ID                 string `db:"id" json:"id"`
	Name               string `db:"name" json:"name"`
	PurchaseCost       int64  `db:"purchase_cost" json:"purchase_cost"`
	UsefulLifeMonths   int64  `db:"useful_life_months" json:"useful_life_months"`
	SalvageValue       int64  `db:"salvage_value" json:"salvage_value"`
	PurchaseMonthIndex int64  `db:"purchase_month_index" json:"purchase_month_index"`
	DepreciationMethod string `db:"depreciation_method" json:"depreciation_method"`
	Status             string `db:"status" json:"status"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) GetCapitalAsset(ctx context.Context, id string) (GetCapitalAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getCapitalAsset, id)
	var i GetCapitalAssetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PurchaseCost,
		&i.UsefulLifeMonths,
		&i.SalvageValue,
		&i.PurchaseMonthIndex,
		&i.DepreciationMethod,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteCapitalAssets = `-- name: ListCompleteCapitalAssets :many
SELECT id, name, purchase_cost, useful_life_months, salvage_value, purchase_month_index, depreciation_method, status, current_step
FROM capital_assets
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteCapitalAssetsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteCapitalAssetsRow struct {
	ID                 string `db:"id" json:"id"`
	Name               string `db:"name" json:"name"`
	PurchaseCost       int64  `db:"purchase_cost" json:"purchase_cost"`
	UsefulLifeMonths   int64  `db:"useful_life_months" json:"useful_life_months"`
	SalvageValue       int64  `db:"salvage_value" json:"salvage_value"`
	PurchaseMonthIndex int64  `db:"purchase_month_index" json:"purchase_month_index"`
	DepreciationMethod string `db:"depreciation_method" json:"depreciation_method"`
	Status             string `db:"status" json:"status"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteCapitalAssets(ctx context.Context, arg ListCompleteCapitalAssetsParams) ([]ListCompleteCapitalAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteCapitalAssets, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteCapitalAssetsRow{}
	for rows.Next() {
		var i ListCompleteCapitalAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PurchaseCost,
			&i.UsefulLifeMonths,
			&i.SalvageValue,
			&i.PurchaseMonthIndex,
			&i.DepreciationMethod,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxCapitalAssetSortOrder = `-- name: MaxCapitalAssetSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM capital_assets WHERE plan_id = ?
`

func (q *Queries) MaxCapitalAssetSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxCapitalAssetSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveCapitalAssetStep = `-- name: SaveCapitalAssetStep :execrows
UPDATE capital_assets
SET name = ?, purchase_cost = ?, useful_life_months = ?, salvage_value = ?, purchase_month_index = ?, depreciation_method = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveCapitalAssetStepParams struct {
	Name               string `db:"name" json:"name"`
	PurchaseCost       int64  `db:"purchase_cost" json:"purchase_cost"`
	UsefulLifeMonths   int64  `db:"useful_life_months" json:"useful_life_months"`
	SalvageValue       int64  `db:"salvage_value" json:"salvage_value"`
	PurchaseMonthIndex int64  `db:"purchase_month_index" json:"purchase_month_index"`
	DepreciationMethod string `db:"depreciation_method" json:"depreciation_method"`
	Status             string `db:"status" json:"status"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
	UpdatedAt          int64  `db:"updated_at" json:"updated_at"`
	ID                 string `db:"id" json:"id"`
}

func (q *Queries) SaveCapitalAssetStep(ctx context.Context, arg SaveCapitalAssetStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveCapitalAssetStep,
		arg.Name,
		arg.PurchaseCost,
		arg.UsefulLifeMonths,
		arg.SalvageValue,
		arg.PurchaseMonthIndex,
		arg.DepreciationMethod,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
