// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: distribution.sql

package db

import (
	"context"
	"database/sql"
)

const createDistributionDraft = `-- name: CreateDistributionDraft :exec
INSERT INTO distributions (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateDistributionDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDistributionDraft(ctx context.Context, arg CreateDistributionDraftParams) error {
	_, err := q.db.ExecContext(ctx, createDistributionDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDistribution = `-- name: DeleteDistribution :execrows
UPDATE distributions SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteDistributionParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteDistribution(ctx context.Context, arg DeleteDistributionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDistribution, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findDistributionDraft = `-- name: FindDistributionDraft :one
SELECT id, name, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM distributions
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindDistributionDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindDistributionDraftRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindDistributionDraft(ctx context.Context, arg FindDistributionDraftParams) (FindDistributionDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findDistributionDraft, arg.PlanID, arg.Status)
	var i FindDistributionDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getDistribution = `-- name: GetDistribution :one
SELECT id, name, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM distributions
WHERE id = ? AND deleted_at IS NULL
`

type GetDistributionRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetDistribution(ctx context.Context, id string) (GetDistributionRow, error) {
	row := q.db.QueryRowContext(ctx, getDistribution, id)
	var i GetDistributionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteDistributions = `-- name: ListCompleteDistributions :many
SELECT id, name, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM distributions
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteDistributionsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteDistributionsRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteDistributions(ctx context.Context, arg ListCompleteDistributionsParams) ([]ListCompleteDistributionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteDistributions, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteDistributionsRow{}
	for rows.Next() {
		var i ListCompleteDistributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyAmount,
			&i.GrowthYr2,
			&i.GrowthYr3,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxDistributionSortOrder = `-- name: MaxDistributionSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM distributions WHERE plan_id = ?
`

func (q *Queries) MaxDistributionSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxDistributionSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveDistributionStep = `-- name: SaveDistributionStep :execrows
UPDATE distributions
SET name = ?, monthly_amount = ?, growth_yr2 = ?, growth_yr3 = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveDistributionStepParams struct {
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) SaveDistributionStep(ctx context.Context, arg SaveDistributionStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveDistributionStep,
		arg.Name,
		arg.MonthlyAmount,
		arg.GrowthYr2,
		arg.GrowthYr3,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
