// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: funding_source.sql

package db

import (
	"context"
	"database/sql"
)

const createFundingSourceDraft = `-- name: CreateFundingSourceDraft :exec
INSERT INTO funding_sources (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateFundingSourceDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateFundingSourceDraft(ctx context.Context, arg CreateFundingSourceDraftParams) error {
	_, err := q.db.ExecContext(ctx, createFundingSourceDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFundingSource = `-- name: DeleteFundingSource :execrows
UPDATE funding_sources SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteFundingSourceParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteFundingSource(ctx context.Context, arg DeleteFundingSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFundingSource, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findFundingSourceDraft = `-- name: FindFundingSourceDraft :one
SELECT id, name, amount, interest_rate, term_months, status, current_step
FROM funding_sources
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindFundingSourceDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindFundingSourceDraftRow struct {
	ID           string  `db:"id" json:"id"`
	Name         string  `db:"name" json:"name"`
	Amount       int64   `db:"amount" json:"amount"`
	InterestRate float64 `db:"interest_rate" json:"interest_rate"`
	TermMonths   int64   `db:"term_months" json:"term_months"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindFundingSourceDraft(ctx context.Context, arg FindFundingSourceDraftParams) (FindFundingSourceDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findFundingSourceDraft, arg.PlanID, arg.Status)
	var i FindFundingSourceDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.InterestRate,
		&i.TermMonths,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getFundingSource = `-- name: GetFundingSource :one
SELECT id, name, amount, interest_rate, term_months, status, current_step
FROM funding_sources
WHERE id = ? AND deleted_at IS NULL
`

type GetFundingSourceRow struct {
	ID           string  `db:"id" json:"id"`
	Name         string  `db:"name" json:"name"`
	Amount       int64   `db:"amount" json:"amount"`
	InterestRate float64 `db:"interest_rate" json:"interest_rate"`
	TermMonths   int64   `db:"term_months" json:"term_months"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetFundingSource(ctx context.Context, id string) (GetFundingSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getFundingSource, id)
	var i GetFundingSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.InterestRate,
		&i.TermMonths,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteFundingSources = `-- name: ListCompleteFundingSources :many
SELECT id, name, amount, interest_rate, term_months, status, current_step
FROM funding_sources
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteFundingSourcesParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteFundingSourcesRow struct {
	ID           string  `db:"id" json:"id"`
	Name         string  `db:"name" json:"name"`
	Amount       int64   `db:"amount" json:"amount"`
	InterestRate float64 `db:"interest_rate" json:"interest_rate"`
	TermMonths   int64   `db:"term_months" json:"term_months"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteFundingSources(ctx context.Context, arg ListCompleteFundingSourcesParams) ([]ListCompleteFundingSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteFundingSources, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteFundingSourcesRow{}
	for rows.Next() {
		var i ListCompleteFundingSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.InterestRate,
			&i.TermMonths,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxFundingSourceSortOrder = `-- name: MaxFundingSourceSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM funding_sources WHERE plan_id = ?
`

func (q *Queries) MaxFundingSourceSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxFundingSourceSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveFundingSourceStep = `-- name: SaveFundingSourceStep :execrows
UPDATE funding_sources
SET name = ?, amount = ?, interest_rate = ?, term_months = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveFundingSourceStepParams struct {
	Name         string  `db:"name" json:"name"`
	Amount       int64   `db:"amount" json:"amount"`
	InterestRate float64 `db:"interest_rate" json:"interest_rate"`
	TermMonths   int64   `db:"term_months" json:"term_months"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
	UpdatedAt    int64   `db:"updated_at" json:"updated_at"`
	ID           string  `db:"id" json:"id"`
}

func (q *Queries) SaveFundingSourceStep(ctx context.Context, arg SaveFundingSourceStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveFundingSourceStep,
		arg.Name,
		arg.Amount,
		arg.InterestRate,
		arg.TermMonths,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
