// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_purchase.sql

package db

import (
	"context"
	"database/sql"
)

const createInventoryPurchaseDraft = `-- name: CreateInventoryPurchaseDraft :exec
INSERT INTO inventory_purchases (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateInventoryPurchaseDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateInventoryPurchaseDraft(ctx context.Context, arg CreateInventoryPurchaseDraftParams) error {
	_, err := q.db.ExecContext(ctx, createInventoryPurchaseDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteInventoryPurchase = `-- name: DeleteInventoryPurchase :execrows
UPDATE inventory_purchases SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteInventoryPurchaseParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteInventoryPurchase(ctx context.Context, arg DeleteInventoryPurchaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInventoryPurchase, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findInventoryPurchaseDraft = `-- name: FindInventoryPurchaseDraft :one
SELECT id, category, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM inventory_purchases
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindInventoryPurchaseDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindInventoryPurchaseDraftRow struct {
	ID            string  `db:"id" json:"id"`
	Category      string  `db:"category" json:"category"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindInventoryPurchaseDraft(ctx context.Context, arg FindInventoryPurchaseDraftParams) (FindInventoryPurchaseDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findInventoryPurchaseDraft, arg.PlanID, arg.Status)
	var i FindInventoryPurchaseDraftRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getInventoryPurchase = `-- name: GetInventoryPurchase :one
SELECT id, category, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM inventory_purchases
WHERE id = ? AND deleted_at IS NULL
`

type GetInventoryPurchaseRow struct {
	ID            string  `db:"id" json:"id"`
	Category      string  `db:"category" json:"category"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetInventoryPurchase(ctx context.Context, id string) (GetInventoryPurchaseRow, error) {
	row := q.db.QueryRowContext(ctx, getInventoryPurchase, id)
	var i GetInventoryPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.MonthlyAmount,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteInventoryPurchases = `-- name: ListCompleteInventoryPurchases :many
SELECT id, category, monthly_amount, growth_yr2, growth_yr3, status, current_step
FROM inventory_purchases
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteInventoryPurchasesParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteInventoryPurchasesRow struct {
	ID            string  `db:"id" json:"id"`
	Category      string  `db:"category" json:"category"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteInventoryPurchases(ctx context.Context, arg ListCompleteInventoryPurchasesParams) ([]ListCompleteInventoryPurchasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteInventoryPurchases, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteInventoryPurchasesRow{}
	for rows.Next() {
		var i ListCompleteInventoryPurchasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.MonthlyAmount,
			&i.GrowthYr2,
			&i.GrowthYr3,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxInventoryPurchaseSortOrder = `-- name: MaxInventoryPurchaseSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM inventory_purchases WHERE plan_id = ?
`

func (q *Queries) MaxInventoryPurchaseSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxInventoryPurchaseSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveInventoryPurchaseStep = `-- name: SaveInventoryPurchaseStep :execrows
UPDATE inventory_purchases
SET category = ?, monthly_amount = ?, growth_yr2 = ?, growth_yr3 = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveInventoryPurchaseStepParams struct {
	Category      string  `db:"category" json:"category"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64 `db:"growth_yr3" json:"growth_yr3"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) SaveInventoryPurchaseStep(ctx context.Context, arg SaveInventoryPurchaseStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveInventoryPurchaseStep,
		arg.Category,
		arg.MonthlyAmount,
		arg.GrowthYr2,
		arg.GrowthYr3,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
