// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package db

import (
	"context"
	"database/sql"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO plan_invites (id, plan_id, email, access_level, status, invited_by, created_at, responded_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
`

type CreateInviteParams struct {
	ID          string `db:"id" json:"id"`
	PlanID      string `db:"plan_id" json:"plan_id"`
	Email       string `db:"email" json:"email"`
	AccessLevel string `db:"access_level" json:"access_level"`
	Status      string `db:"status" json:"status"`
	InvitedBy   string `db:"invited_by" json:"invited_by"`
	CreatedAt   int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.PlanID,
		arg.Email,
		arg.AccessLevel,
		arg.Status,
		arg.InvitedBy,
		arg.CreatedAt,
	)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT plan_id, email, access_level, status, invited_by, created_at, responded_at
FROM plan_invites WHERE id = ?
`

type GetInviteRow struct {
	PlanID      string        `db:"plan_id" json:"plan_id"`
	Email       string        `db:"email" json:"email"`
	AccessLevel string        `db:"access_level" json:"access_level"`
	Status      string        `db:"status" json:"status"`
	InvitedBy   string        `db:"invited_by" json:"invited_by"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	RespondedAt sql.NullInt64 `db:"responded_at" json:"responded_at"`
}

func (q *Queries) GetInvite(ctx context.Context, id string) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i GetInviteRow
	err := row.Scan(
		&i.PlanID,
		&i.Email,
		&i.AccessLevel,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getInvitesForPlan = `-- name: GetInvitesForPlan :many
SELECT id, email, access_level, status, invited_by, created_at, responded_at
FROM plan_invites WHERE plan_id = ? ORDER BY created_at DESC
`

type GetInvitesForPlanRow struct {
	ID          string        `db:"id" json:"id"`
	Email       string        `db:"email" json:"email"`
	AccessLevel string        `db:"access_level" json:"access_level"`
	Status      string        `db:"status" json:"status"`
	InvitedBy   string        `db:"invited_by" json:"invited_by"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	RespondedAt sql.NullInt64 `db:"responded_at" json:"responded_at"`
}

func (q *Queries) GetInvitesForPlan(ctx context.Context, planID string) ([]GetInvitesForPlanRow, error) {
	rows, err := q.db.QueryContext(ctx, getInvitesForPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInvitesForPlanRow{}
	for rows.Next() {
		var i GetInvitesForPlanRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AccessLevel,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingInvitesForEmail = `-- name: GetPendingInvitesForEmail :many
SELECT id, plan_id, access_level, status, invited_by, created_at, responded_at
FROM plan_invites WHERE LOWER(email) = ? AND status = ? ORDER BY created_at DESC
`

type GetPendingInvitesForEmailParams struct {
	Email  string `db:"email" json:"email"`
	Status string `db:"status" json:"status"`
}

type GetPendingInvitesForEmailRow struct {
	ID          string        `db:"id" json:"id"`
	PlanID      string        `db:"plan_id" json:"plan_id"`
	AccessLevel string        `db:"access_level" json:"access_level"`
	Status      string        `db:"status" json:"status"`
	InvitedBy   string        `db:"invited_by" json:"invited_by"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	RespondedAt sql.NullInt64 `db:"responded_at" json:"responded_at"`
}

func (q *Queries) GetPendingInvitesForEmail(ctx context.Context, arg GetPendingInvitesForEmailParams) ([]GetPendingInvitesForEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvitesForEmail, arg.Email, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingInvitesForEmailRow{}
	for rows.Next() {
		var i GetPendingInvitesForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.AccessLevel,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInviteStatus = `-- name: UpdateInviteStatus :execrows
UPDATE plan_invites SET status = ?, responded_at = ? WHERE id = ?
`

type UpdateInviteStatusParams struct {
	Status      string        `db:"status" json:"status"`
	RespondedAt sql.NullInt64 `db:"responded_at" json:"responded_at"`
	ID          string        `db:"id" json:"id"`
}

func (q *Queries) UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInviteStatus, arg.Status, arg.RespondedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
