// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Benefit struct {
	ID            string        `db:"id" json:"id"`
	PlanID        string        `db:"plan_id" json:"plan_id"`
	Type          string        `db:"type" json:"type"`
	MonthlyAmount int64         `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64       `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64       `db:"growth_yr3" json:"growth_yr3"`
	Status        string        `db:"status" json:"status"`
	CurrentStep   int64         `db:"current_step" json:"current_step"`
	SortOrder     int64         `db:"sort_order" json:"sort_order"`
	CreatedAt     int64         `db:"created_at" json:"created_at"`
	UpdatedAt     int64         `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type CapitalAsset struct {
	ID                 string        `db:"id" json:"id"`
	PlanID             string        `db:"plan_id" json:"plan_id"`
	Name               string        `db:"name" json:"name"`
	PurchaseCost       int64         `db:"purchase_cost" json:"purchase_cost"`
	UsefulLifeMonths   int64         `db:"useful_life_months" json:"useful_life_months"`
	SalvageValue       int64         `db:"salvage_value" json:"salvage_value"`
	PurchaseMonthIndex int64         `db:"purchase_month_index" json:"purchase_month_index"`
	DepreciationMethod string        `db:"depreciation_method" json:"depreciation_method"`
	Status             string        `db:"status" json:"status"`
	CurrentStep        int64         `db:"current_step" json:"current_step"`
	SortOrder          int64         `db:"sort_order" json:"sort_order"`
	CreatedAt          int64         `db:"created_at" json:"created_at"`
	UpdatedAt          int64         `db:"updated_at" json:"updated_at"`
	DeletedAt          sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type Distribution struct {
	ID            string        `db:"id" json:"id"`
	PlanID        string        `db:"plan_id" json:"plan_id"`
	Name          string        `db:"name" json:"name"`
	MonthlyAmount int64         `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64       `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64       `db:"growth_yr3" json:"growth_yr3"`
	Status        string        `db:"status" json:"status"`
	CurrentStep   int64         `db:"current_step" json:"current_step"`
	SortOrder     int64         `db:"sort_order" json:"sort_order"`
	CreatedAt     int64         `db:"created_at" json:"created_at"`
	UpdatedAt     int64         `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type FundingSource struct {
	ID           string        `db:"id" json:"id"`
	PlanID       string        `db:"plan_id" json:"plan_id"`
	Name         string        `db:"name" json:"name"`
	Amount       int64         `db:"amount" json:"amount"`
	InterestRate float64       `db:"interest_rate" json:"interest_rate"`
	TermMonths   int64         `db:"term_months" json:"term_months"`
	Status       string        `db:"status" json:"status"`
	CurrentStep  int64         `db:"current_step" json:"current_step"`
	SortOrder    int64         `db:"sort_order" json:"sort_order"`
	CreatedAt    int64         `db:"created_at" json:"created_at"`
	UpdatedAt    int64         `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type IdempotencyKey struct {
	Key       string         `db:"key" json:"key"`
	Status    string         `db:"status" json:"status"`
	Response  sql.NullString `db:"response" json:"response"`
	CreatedAt int64          `db:"created_at" json:"created_at"`
	UpdatedAt int64          `db:"updated_at" json:"updated_at"`
}

type InventoryPurchase struct {
	ID            string        `db:"id" json:"id"`
	PlanID        string        `db:"plan_id" json:"plan_id"`
	Category      string        `db:"category" json:"category"`
	MonthlyAmount int64         `db:"monthly_amount" json:"monthly_amount"`
	GrowthYr2     float64       `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3     float64       `db:"growth_yr3" json:"growth_yr3"`
	Status        string        `db:"status" json:"status"`
	CurrentStep   int64         `db:"current_step" json:"current_step"`
	SortOrder     int64         `db:"sort_order" json:"sort_order"`
	CreatedAt     int64         `db:"created_at" json:"created_at"`
	UpdatedAt     int64         `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type OperatingExpense struct {
	ID            string        `db:"id" json:"id"`
	PlanID        string        `db:"plan_id" json:"plan_id"`
	Name          string        `db:"name" json:"name"`
	MonthlyAmount int64         `db:"monthly_amount" json:"monthly_amount"`
	GrowthType    string        `db:"growth_type" json:"growth_type"`
	AnnualRate    float64       `db:"annual_rate" json:"annual_rate"`
	Status        string        `db:"status" json:"status"`
	CurrentStep   int64         `db:"current_step" json:"current_step"`
	SortOrder     int64         `db:"sort_order" json:"sort_order"`
	CreatedAt     int64         `db:"created_at" json:"created_at"`
	UpdatedAt     int64         `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type OutboxEvent struct {
	ID          string        `db:"id" json:"id"`
	EventName   string        `db:"event_name" json:"event_name"`
	Payload     string        `db:"payload" json:"payload"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	ProcessedAt sql.NullInt64 `db:"processed_at" json:"processed_at"`
}

type PayrollTaxRate struct {
	PlanID             string  `db:"plan_id" json:"plan_id"`
	SocialSecurityRate float64 `db:"social_security_rate" json:"social_security_rate"`
	MedicareRate       float64 `db:"medicare_rate" json:"medicare_rate"`
	FutaRate           float64 `db:"futa_rate" json:"futa_rate"`
	SutaRate           float64 `db:"suta_rate" json:"suta_rate"`
	CurrentStep        int64   `db:"current_step" json:"current_step"`
	CreatedAt          int64   `db:"created_at" json:"created_at"`
	UpdatedAt          int64   `db:"updated_at" json:"updated_at"`
}

type Plan struct {
	ID        string        `db:"id" json:"id"`
	Data      []byte        `db:"data" json:"data"`
	CreatedAt int64         `db:"created_at" json:"created_at"`
	UpdatedAt int64         `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type PlanAccess struct {
	PlanID      string `db:"plan_id" json:"plan_id"`
	UserID      string `db:"user_id" json:"user_id"`
	AccessLevel string `db:"access_level" json:"access_level"`
	InvitedAt   int64  `db:"invited_at" json:"invited_at"`
}

type PlanInvite struct {
	ID          string        `db:"id" json:"id"`
	PlanID      string        `db:"plan_id" json:"plan_id"`
	Email       string        `db:"email" json:"email"`
	AccessLevel string        `db:"access_level" json:"access_level"`
	Status      string        `db:"status" json:"status"`
	InvitedBy   string        `db:"invited_by" json:"invited_by"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	RespondedAt sql.NullInt64 `db:"responded_at" json:"responded_at"`
}

type Product struct {
	ID           string        `db:"id" json:"id"`
	PlanID       string        `db:"plan_id" json:"plan_id"`
	Name         string        `db:"name" json:"name"`
	Month1Units  int64         `db:"month1_units" json:"month1_units"`
	PricePerUnit int64         `db:"price_per_unit" json:"price_per_unit"`
	CostPerUnit  int64         `db:"cost_per_unit" json:"cost_per_unit"`
	Status       string        `db:"status" json:"status"`
	CurrentStep  int64         `db:"current_step" json:"current_step"`
	SortOrder    int64         `db:"sort_order" json:"sort_order"`
	CreatedAt    int64         `db:"created_at" json:"created_at"`
	UpdatedAt    int64         `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type SalaryRole struct {
	ID           string        `db:"id" json:"id"`
	PlanID       string        `db:"plan_id" json:"plan_id"`
	Role         string        `db:"role" json:"role"`
	IsContractor int64         `db:"is_contractor" json:"is_contractor"`
	Headcount    int64         `db:"headcount" json:"headcount"`
	MonthlyPay   int64         `db:"monthly_pay" json:"monthly_pay"`
	GrowthYr2    float64       `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3    float64       `db:"growth_yr3" json:"growth_yr3"`
	Status       string        `db:"status" json:"status"`
	CurrentStep  int64         `db:"current_step" json:"current_step"`
	SortOrder    int64         `db:"sort_order" json:"sort_order"`
	CreatedAt    int64         `db:"created_at" json:"created_at"`
	UpdatedAt    int64         `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type SalesGrowthCurve struct {
	PlanID      string  `db:"plan_id" json:"plan_id"`
	Y1Q1        float64 `db:"y1_q1" json:"y1_q1"`
	Y1Q2        float64 `db:"y1_q2" json:"y1_q2"`
	Y1Q3        float64 `db:"y1_q3" json:"y1_q3"`
	Y1Q4        float64 `db:"y1_q4" json:"y1_q4"`
	GrowthYr2   float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3   float64 `db:"growth_yr3" json:"growth_yr3"`
	CurrentStep int64   `db:"current_step" json:"current_step"`
	CreatedAt   int64   `db:"created_at" json:"created_at"`
	UpdatedAt   int64   `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID        string `db:"id" json:"id"`
	UserID    string `db:"user_id" json:"user_id"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	ExpiresAt int64  `db:"expires_at" json:"expires_at"`
}

type StartingBalance struct {
	PlanID             string `db:"plan_id" json:"plan_id"`
	Cash               int64  `db:"cash" json:"cash"`
	AccountsReceivable int64  `db:"accounts_receivable" json:"accounts_receivable"`
	PrepaidExpenses    int64  `db:"prepaid_expenses" json:"prepaid_expenses"`
	AccountsPayable    int64  `db:"accounts_payable" json:"accounts_payable"`
	AccruedExpenses    int64  `db:"accrued_expenses" json:"accrued_expenses"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
	CreatedAt          int64  `db:"created_at" json:"created_at"`
	UpdatedAt          int64  `db:"updated_at" json:"updated_at"`
}

type StartupCost struct {
	ID          string        `db:"id" json:"id"`
	PlanID      string        `db:"plan_id" json:"plan_id"`
	Name        string        `db:"name" json:"name"`
	Amount      int64         `db:"amount" json:"amount"`
	Status      string        `db:"status" json:"status"`
	CurrentStep int64         `db:"current_step" json:"current_step"`
	SortOrder   int64         `db:"sort_order" json:"sort_order"`
	CreatedAt   int64         `db:"created_at" json:"created_at"`
	UpdatedAt   int64         `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        string `db:"id" json:"id"`
	Email     string `db:"email" json:"email"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
}

type UsersCredential struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	CreatedAt    int64  `db:"created_at" json:"created_at"`
}

type WizardSection struct {
	PlanID      string        `db:"plan_id" json:"plan_id"`
	Hub         string        `db:"hub" json:"hub"`
	Section     string        `db:"section" json:"section"`
	CompletedAt sql.NullInt64 `db:"completed_at" json:"completed_at"`
}
