// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operating_expense.sql

package db

import (
	"context"
	"database/sql"
)

const createOperatingExpenseDraft = `-- name: CreateOperatingExpenseDraft :exec
INSERT INTO operating_expenses (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateOperatingExpenseDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateOperatingExpenseDraft(ctx context.Context, arg CreateOperatingExpenseDraftParams) error {
	_, err := q.db.ExecContext(ctx, createOperatingExpenseDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOperatingExpense = `-- name: DeleteOperatingExpense :execrows
UPDATE operating_expenses SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteOperatingExpenseParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteOperatingExpense(ctx context.Context, arg DeleteOperatingExpenseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOperatingExpense, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findOperatingExpenseDraft = `-- name: FindOperatingExpenseDraft :one
SELECT id, name, monthly_amount, growth_type, annual_rate, status, current_step
FROM operating_expenses
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindOperatingExpenseDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindOperatingExpenseDraftRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthType    string  `db:"growth_type" json:"growth_type"`
	AnnualRate    float64 `db:"annual_rate" json:"annual_rate"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindOperatingExpenseDraft(ctx context.Context, arg FindOperatingExpenseDraftParams) (FindOperatingExpenseDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findOperatingExpenseDraft, arg.PlanID, arg.Status)
	var i FindOperatingExpenseDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyAmount,
		&i.GrowthType,
		&i.AnnualRate,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getOperatingExpense = `-- name: GetOperatingExpense :one
SELECT id, name, monthly_amount, growth_type, annual_rate, status, current_step
FROM operating_expenses
WHERE id = ? AND deleted_at IS NULL
`

type GetOperatingExpenseRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthType    string  `db:"growth_type" json:"growth_type"`
	AnnualRate    float64 `db:"annual_rate" json:"annual_rate"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetOperatingExpense(ctx context.Context, id string) (GetOperatingExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, getOperatingExpense, id)
	var i GetOperatingExpenseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyAmount,
		&i.GrowthType,
		&i.AnnualRate,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteOperatingExpenses = `-- name: ListCompleteOperatingExpenses :many
SELECT id, name, monthly_amount, growth_type, annual_rate, status, current_step
FROM operating_expenses
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteOperatingExpensesParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteOperatingExpensesRow struct {
	ID            string  `db:"id" json:"id"`
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthType    string  `db:"growth_type" json:"growth_type"`
	AnnualRate    float64 `db:"annual_rate" json:"annual_rate"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteOperatingExpenses(ctx context.Context, arg ListCompleteOperatingExpensesParams) ([]ListCompleteOperatingExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteOperatingExpenses, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteOperatingExpensesRow{}
	for rows.Next() {
		var i ListCompleteOperatingExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyAmount,
			&i.GrowthType,
			&i.AnnualRate,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOperatingExpenseSortOrder = `-- name: MaxOperatingExpenseSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM operating_expenses WHERE plan_id = ?
`

func (q *Queries) MaxOperatingExpenseSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxOperatingExpenseSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveOperatingExpenseStep = `-- name: SaveOperatingExpenseStep :execrows
UPDATE operating_expenses
SET name = ?, monthly_amount = ?, growth_type = ?, annual_rate = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveOperatingExpenseStepParams struct {
	Name          string  `db:"name" json:"name"`
	MonthlyAmount int64   `db:"monthly_amount" json:"monthly_amount"`
	GrowthType    string  `db:"growth_type" json:"growth_type"`
	AnnualRate    float64 `db:"annual_rate" json:"annual_rate"`
	Status        string  `db:"status" json:"status"`
	CurrentStep   int64   `db:"current_step" json:"current_step"`
	UpdatedAt     int64   `db:"updated_at" json:"updated_at"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) SaveOperatingExpenseStep(ctx context.Context, arg SaveOperatingExpenseStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveOperatingExpenseStep,
		arg.Name,
		arg.MonthlyAmount,
		arg.GrowthType,
		arg.AnnualRate,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
