// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, event_name, payload, created_at) VALUES (?, ?, ?, ?)
`

type InsertOutboxEventParams struct {
	ID        string `db:"id" json:"id"`
	EventName string `db:"event_name" json:"event_name"`
	Payload   string `db:"payload" json:"payload"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEvent,
		arg.ID,
		arg.EventName,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}
