// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payroll_tax_rates.sql

package db

import (
	"context"
)

const getPayrollTaxRatesRow = `-- name: GetPayrollTaxRatesRow :one
SELECT social_security_rate, medicare_rate, futa_rate, suta_rate, current_step
FROM payroll_tax_rates WHERE plan_id = ?
`

type GetPayrollTaxRatesRowRow struct {
	SocialSecurityRate float64 `db:"social_security_rate" json:"social_security_rate"`
	MedicareRate       float64 `db:"medicare_rate" json:"medicare_rate"`
	FutaRate           float64 `db:"futa_rate" json:"futa_rate"`
	SutaRate           float64 `db:"suta_rate" json:"suta_rate"`
	CurrentStep        int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetPayrollTaxRatesRow(ctx context.Context, planID string) (GetPayrollTaxRatesRowRow, error) {
	row := q.db.QueryRowContext(ctx, getPayrollTaxRatesRow, planID)
	var i GetPayrollTaxRatesRowRow
	err := row.Scan(
		&i.SocialSecurityRate,
		&i.MedicareRate,
		&i.FutaRate,
		&i.SutaRate,
		&i.CurrentStep,
	)
	return i, err
}

const savePayrollTaxRatesStep = `-- name: SavePayrollTaxRatesStep :exec
INSERT INTO payroll_tax_rates (plan_id, social_security_rate, medicare_rate, futa_rate, suta_rate, current_step, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plan_id) DO UPDATE SET
	social_security_rate = excluded.social_security_rate,
	medicare_rate = excluded.medicare_rate,
	futa_rate = excluded.futa_rate,
	suta_rate = excluded.suta_rate,
	current_step = excluded.current_step,
	updated_at = excluded.updated_at
`

type SavePayrollTaxRatesStepParams struct {
	PlanID             string  `db:"plan_id" json:"plan_id"`
	SocialSecurityRate float64 `db:"social_security_rate" json:"social_security_rate"`
	MedicareRate       float64 `db:"medicare_rate" json:"medicare_rate"`
	FutaRate           float64 `db:"futa_rate" json:"futa_rate"`
	SutaRate           float64 `db:"suta_rate" json:"suta_rate"`
	CurrentStep        int64   `db:"current_step" json:"current_step"`
	CreatedAt          int64   `db:"created_at" json:"created_at"`
	UpdatedAt          int64   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SavePayrollTaxRatesStep(ctx context.Context, arg SavePayrollTaxRatesStepParams) error {
	_, err := q.db.ExecContext(ctx, savePayrollTaxRatesStep,
		arg.PlanID,
		arg.SocialSecurityRate,
		arg.MedicareRate,
		arg.FutaRate,
		arg.SutaRate,
		arg.CurrentStep,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
