// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"
	"database/sql"
)

const deletePayrollTaxRatesByPlan = `-- name: DeletePayrollTaxRatesByPlan :exec
DELETE FROM payroll_tax_rates WHERE plan_id = ?
`

func (q *Queries) DeletePayrollTaxRatesByPlan(ctx context.Context, planID string) error {
	_, err := q.db.ExecContext(ctx, deletePayrollTaxRatesByPlan, planID)
	return err
}

const deletePlanAccessByPlan = `-- name: DeletePlanAccessByPlan :exec
DELETE FROM plan_access WHERE plan_id = ?
`

func (q *Queries) DeletePlanAccessByPlan(ctx context.Context, planID string) error {
	_, err := q.db.ExecContext(ctx, deletePlanAccessByPlan, planID)
	return err
}

const deleteSalesGrowthCurveByPlan = `-- name: DeleteSalesGrowthCurveByPlan :exec
DELETE FROM sales_growth_curve WHERE plan_id = ?
`

func (q *Queries) DeleteSalesGrowthCurveByPlan(ctx context.Context, planID string) error {
	_, err := q.db.ExecContext(ctx, deleteSalesGrowthCurveByPlan, planID)
	return err
}

const deleteStartingBalancesByPlan = `-- name: DeleteStartingBalancesByPlan :exec
DELETE FROM starting_balances WHERE plan_id = ?
`

func (q *Queries) DeleteStartingBalancesByPlan(ctx context.Context, planID string) error {
	_, err := q.db.ExecContext(ctx, deleteStartingBalancesByPlan, planID)
	return err
}

const deleteWizardSectionsByPlan = `-- name: DeleteWizardSectionsByPlan :exec
DELETE FROM wizard_sections WHERE plan_id = ?
`

func (q *Queries) DeleteWizardSectionsByPlan(ctx context.Context, planID string) error {
	_, err := q.db.ExecContext(ctx, deleteWizardSectionsByPlan, planID)
	return err
}

const getAllPlans = `-- name: GetAllPlans :many
SELECT data FROM plans WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) GetAllPlans(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlan = `-- name: GetPlan :one
SELECT data FROM plans WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetPlan(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getUserPlans = `-- name: GetUserPlans :many
SELECT p.data
FROM plans p
JOIN plan_access pa ON p.id = pa.plan_id
WHERE pa.user_id = ? AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
`

func (q *Queries) GetUserPlans(ctx context.Context, userID string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, getUserPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePlan = `-- name: SavePlan :exec
INSERT INTO plans (id, data, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = excluded.updated_at
`

type SavePlanParams struct {
	ID        string `db:"id" json:"id"`
	Data      []byte `db:"data" json:"data"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SavePlan(ctx context.Context, arg SavePlanParams) error {
	_, err := q.db.ExecContext(ctx, savePlan,
		arg.ID,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const softDeleteBenefitsByPlan = `-- name: SoftDeleteBenefitsByPlan :exec
UPDATE benefits SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteBenefitsByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteBenefitsByPlan(ctx context.Context, arg SoftDeleteBenefitsByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteBenefitsByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteCapitalAssetsByPlan = `-- name: SoftDeleteCapitalAssetsByPlan :exec
UPDATE capital_assets SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteCapitalAssetsByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteCapitalAssetsByPlan(ctx context.Context, arg SoftDeleteCapitalAssetsByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCapitalAssetsByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteDistributionsByPlan = `-- name: SoftDeleteDistributionsByPlan :exec
UPDATE distributions SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteDistributionsByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteDistributionsByPlan(ctx context.Context, arg SoftDeleteDistributionsByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDistributionsByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteFundingSourcesByPlan = `-- name: SoftDeleteFundingSourcesByPlan :exec
UPDATE funding_sources SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteFundingSourcesByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteFundingSourcesByPlan(ctx context.Context, arg SoftDeleteFundingSourcesByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFundingSourcesByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteInventoryPurchasesByPlan = `-- name: SoftDeleteInventoryPurchasesByPlan :exec
UPDATE inventory_purchases SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteInventoryPurchasesByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteInventoryPurchasesByPlan(ctx context.Context, arg SoftDeleteInventoryPurchasesByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteInventoryPurchasesByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteOperatingExpensesByPlan = `-- name: SoftDeleteOperatingExpensesByPlan :exec
UPDATE operating_expenses SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteOperatingExpensesByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteOperatingExpensesByPlan(ctx context.Context, arg SoftDeleteOperatingExpensesByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteOperatingExpensesByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeletePlan = `-- name: SoftDeletePlan :execrows
UPDATE plans SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeletePlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeletePlan, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteProductsByPlan = `-- name: SoftDeleteProductsByPlan :exec
UPDATE products SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteProductsByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteProductsByPlan(ctx context.Context, arg SoftDeleteProductsByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteProductsByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteSalaryRolesByPlan = `-- name: SoftDeleteSalaryRolesByPlan :exec
UPDATE salary_roles SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteSalaryRolesByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteSalaryRolesByPlan(ctx context.Context, arg SoftDeleteSalaryRolesByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSalaryRolesByPlan, arg.DeletedAt, arg.PlanID)
	return err
}

const softDeleteStartupCostsByPlan = `-- name: SoftDeleteStartupCostsByPlan :exec
UPDATE startup_costs SET deleted_at = ? WHERE plan_id = ?
`

type SoftDeleteStartupCostsByPlanParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	PlanID    string        `db:"plan_id" json:"plan_id"`
}

func (q *Queries) SoftDeleteStartupCostsByPlan(ctx context.Context, arg SoftDeleteStartupCostsByPlanParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteStartupCostsByPlan, arg.DeletedAt, arg.PlanID)
	return err
}
