// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"
	"database/sql"
)

const createProductDraft = `-- name: CreateProductDraft :exec
INSERT INTO products (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateProductDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProductDraft(ctx context.Context, arg CreateProductDraftParams) error {
	_, err := q.db.ExecContext(ctx, createProductDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :execrows
UPDATE products SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteProductParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProduct, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findProductDraft = `-- name: FindProductDraft :one
SELECT id, name, month1_units, price_per_unit, cost_per_unit, status, current_step
FROM products
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindProductDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindProductDraftRow struct {
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Month1Units  int64  `db:"month1_units" json:"month1_units"`
	PricePerUnit int64  `db:"price_per_unit" json:"price_per_unit"`
	CostPerUnit  int64  `db:"cost_per_unit" json:"cost_per_unit"`
	Status       string `db:"status" json:"status"`
	CurrentStep  int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) FindProductDraft(ctx context.Context, arg FindProductDraftParams) (FindProductDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findProductDraft, arg.PlanID, arg.Status)
	var i FindProductDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Month1Units,
		&i.PricePerUnit,
		&i.CostPerUnit,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, month1_units, price_per_unit, cost_per_unit, status, current_step
FROM products
WHERE id = ? AND deleted_at IS NULL
`

type GetProductRow struct {
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Month1Units  int64  `db:"month1_units" json:"month1_units"`
	PricePerUnit int64  `db:"price_per_unit" json:"price_per_unit"`
	CostPerUnit  int64  `db:"cost_per_unit" json:"cost_per_unit"`
	Status       string `db:"status" json:"status"`
	CurrentStep  int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) GetProduct(ctx context.Context, id string) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Month1Units,
		&i.PricePerUnit,
		&i.CostPerUnit,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteProducts = `-- name: ListCompleteProducts :many
SELECT id, name, month1_units, price_per_unit, cost_per_unit, status, current_step
FROM products
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteProductsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteProductsRow struct {
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Month1Units  int64  `db:"month1_units" json:"month1_units"`
	PricePerUnit int64  `db:"price_per_unit" json:"price_per_unit"`
	CostPerUnit  int64  `db:"cost_per_unit" json:"cost_per_unit"`
	Status       string `db:"status" json:"status"`
	CurrentStep  int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteProducts(ctx context.Context, arg ListCompleteProductsParams) ([]ListCompleteProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteProducts, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteProductsRow{}
	for rows.Next() {
		var i ListCompleteProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Month1Units,
			&i.PricePerUnit,
			&i.CostPerUnit,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxProductSortOrder = `-- name: MaxProductSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM products WHERE plan_id = ?
`

func (q *Queries) MaxProductSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxProductSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveProductStep = `-- name: SaveProductStep :execrows
UPDATE products
SET name = ?, month1_units = ?, price_per_unit = ?, cost_per_unit = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveProductStepParams struct {
	Name         string `db:"name" json:"name"`
	Month1Units  int64  `db:"month1_units" json:"month1_units"`
	PricePerUnit int64  `db:"price_per_unit" json:"price_per_unit"`
	CostPerUnit  int64  `db:"cost_per_unit" json:"cost_per_unit"`
	Status       string `db:"status" json:"status"`
	CurrentStep  int64  `db:"current_step" json:"current_step"`
	UpdatedAt    int64  `db:"updated_at" json:"updated_at"`
	ID           string `db:"id" json:"id"`
}

func (q *Queries) SaveProductStep(ctx context.Context, arg SaveProductStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveProductStep,
		arg.Name,
		arg.Month1Units,
		arg.PricePerUnit,
		arg.CostPerUnit,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
