// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountPlanExists(ctx context.Context, id string) (int64, error)
	CountUserExists(ctx context.Context, id string) (int64, error)
	CreateBenefitDraft(ctx context.Context, arg CreateBenefitDraftParams) error
	CreateCapitalAssetDraft(ctx context.Context, arg CreateCapitalAssetDraftParams) error
	CreateDistributionDraft(ctx context.Context, arg CreateDistributionDraftParams) error
	CreateFundingSourceDraft(ctx context.Context, arg CreateFundingSourceDraftParams) error
	CreateInventoryPurchaseDraft(ctx context.Context, arg CreateInventoryPurchaseDraftParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateOperatingExpenseDraft(ctx context.Context, arg CreateOperatingExpenseDraftParams) error
	CreateProductDraft(ctx context.Context, arg CreateProductDraftParams) error
	CreateSalaryRoleDraft(ctx context.Context, arg CreateSalaryRoleDraftParams) error
	CreateStartupCostDraft(ctx context.Context, arg CreateStartupCostDraftParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteBenefit(ctx context.Context, arg DeleteBenefitParams) (int64, error)
	DeleteCapitalAsset(ctx context.Context, arg DeleteCapitalAssetParams) (int64, error)
	DeleteDistribution(ctx context.Context, arg DeleteDistributionParams) (int64, error)
	DeleteFundingSource(ctx context.Context, arg DeleteFundingSourceParams) (int64, error)
	DeleteInventoryPurchase(ctx context.Context, arg DeleteInventoryPurchaseParams) (int64, error)
	DeleteOperatingExpense(ctx context.Context, arg DeleteOperatingExpenseParams) (int64, error)
	DeletePayrollTaxRatesByPlan(ctx context.Context, planID string) error
	DeletePlanAccessByPlan(ctx context.Context, planID string) error
	DeletePlanAccessByUser(ctx context.Context, userID string) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error)
	DeleteSalaryRole(ctx context.Context, arg DeleteSalaryRoleParams) (int64, error)
	DeleteSalesGrowthCurveByPlan(ctx context.Context, planID string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUser(ctx context.Context, userID string) error
	DeleteStartingBalancesByPlan(ctx context.Context, planID string) error
	DeleteStartupCost(ctx context.Context, arg DeleteStartupCostParams) (int64, error)
	DeleteUserCredentialsByEmail(ctx context.Context, email string) error
	DeleteWizardSectionsByPlan(ctx context.Context, planID string) error
	FindBenefitDraft(ctx context.Context, arg FindBenefitDraftParams) (FindBenefitDraftRow, error)
	FindCapitalAssetDraft(ctx context.Context, arg FindCapitalAssetDraftParams) (FindCapitalAssetDraftRow, error)
	FindDistributionDraft(ctx context.Context, arg FindDistributionDraftParams) (FindDistributionDraftRow, error)
	FindFundingSourceDraft(ctx context.Context, arg FindFundingSourceDraftParams) (FindFundingSourceDraftRow, error)
	FindInventoryPurchaseDraft(ctx context.Context, arg FindInventoryPurchaseDraftParams) (FindInventoryPurchaseDraftRow, error)
	FindOperatingExpenseDraft(ctx context.Context, arg FindOperatingExpenseDraftParams) (FindOperatingExpenseDraftRow, error)
	FindProductDraft(ctx context.Context, arg FindProductDraftParams) (FindProductDraftRow, error)
	FindSalaryRoleDraft(ctx context.Context, arg FindSalaryRoleDraftParams) (FindSalaryRoleDraftRow, error)
	FindStartupCostDraft(ctx context.Context, arg FindStartupCostDraftParams) (FindStartupCostDraftRow, error)
	GetAccess(ctx context.Context, arg GetAccessParams) (GetAccessRow, error)
	GetAllPlans(ctx context.Context) ([][]byte, error)
	GetBenefit(ctx context.Context, id string) (GetBenefitRow, error)
	GetCapitalAsset(ctx context.Context, id string) (GetCapitalAssetRow, error)
	GetDistribution(ctx context.Context, id string) (GetDistributionRow, error)
	GetFundingSource(ctx context.Context, id string) (GetFundingSourceRow, error)
	GetInventoryPurchase(ctx context.Context, id string) (GetInventoryPurchaseRow, error)
	GetInvite(ctx context.Context, id string) (GetInviteRow, error)
	GetInvitesForPlan(ctx context.Context, planID string) ([]GetInvitesForPlanRow, error)
	GetOperatingExpense(ctx context.Context, id string) (GetOperatingExpenseRow, error)
	GetPayrollTaxRatesRow(ctx context.Context, planID string) (GetPayrollTaxRatesRowRow, error)
	GetPendingInvitesForEmail(ctx context.Context, arg GetPendingInvitesForEmailParams) ([]GetPendingInvitesForEmailRow, error)
	GetPlan(ctx context.Context, id string) ([]byte, error)
	GetPlanAccess(ctx context.Context, planID string) ([]GetPlanAccessRow, error)
	GetPlansForUser(ctx context.Context, userID string) ([][]byte, error)
	GetProduct(ctx context.Context, id string) (GetProductRow, error)
	GetSalaryRole(ctx context.Context, id string) (GetSalaryRoleRow, error)
	GetSalesGrowthCurveRow(ctx context.Context, planID string) (GetSalesGrowthCurveRowRow, error)
	GetSession(ctx context.Context, id string) (GetSessionRow, error)
	GetStartingBalancesRow(ctx context.Context, planID string) (GetStartingBalancesRowRow, error)
	GetStartupCost(ctx context.Context, id string) (GetStartupCostRow, error)
	GetUnpublishedOutboxEvents(ctx context.Context, limit int64) ([]OutboxEvent, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error)
	GetUserIDByEmail(ctx context.Context, email string) (string, error)
	GetUserPlans(ctx context.Context, userID string) ([][]byte, error)
	GrantAccess(ctx context.Context, arg GrantAccessParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListCompleteBenefits(ctx context.Context, arg ListCompleteBenefitsParams) ([]ListCompleteBenefitsRow, error)
	ListCompleteCapitalAssets(ctx context.Context, arg ListCompleteCapitalAssetsParams) ([]ListCompleteCapitalAssetsRow, error)
	ListCompleteDistributions(ctx context.Context, arg ListCompleteDistributionsParams) ([]ListCompleteDistributionsRow, error)
	ListCompleteFundingSources(ctx context.Context, arg ListCompleteFundingSourcesParams) ([]ListCompleteFundingSourcesRow, error)
	ListCompleteInventoryPurchases(ctx context.Context, arg ListCompleteInventoryPurchasesParams) ([]ListCompleteInventoryPurchasesRow, error)
	ListCompleteOperatingExpenses(ctx context.Context, arg ListCompleteOperatingExpensesParams) ([]ListCompleteOperatingExpensesRow, error)
	ListCompleteProducts(ctx context.Context, arg ListCompleteProductsParams) ([]ListCompleteProductsRow, error)
	ListCompleteSalaryRoles(ctx context.Context, arg ListCompleteSalaryRolesParams) ([]ListCompleteSalaryRolesRow, error)
	ListCompleteStartupCosts(ctx context.Context, arg ListCompleteStartupCostsParams) ([]ListCompleteStartupCostsRow, error)
	ListWizardSections(ctx context.Context, arg ListWizardSectionsParams) ([]ListWizardSectionsRow, error)
	MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) error
	MaxBenefitSortOrder(ctx context.Context, planID string) (int64, error)
	MaxCapitalAssetSortOrder(ctx context.Context, planID string) (int64, error)
	MaxDistributionSortOrder(ctx context.Context, planID string) (int64, error)
	MaxFundingSourceSortOrder(ctx context.Context, planID string) (int64, error)
	MaxInventoryPurchaseSortOrder(ctx context.Context, planID string) (int64, error)
	MaxOperatingExpenseSortOrder(ctx context.Context, planID string) (int64, error)
	MaxProductSortOrder(ctx context.Context, planID string) (int64, error)
	MaxSalaryRoleSortOrder(ctx context.Context, planID string) (int64, error)
	MaxStartupCostSortOrder(ctx context.Context, planID string) (int64, error)
	SaveBenefitStep(ctx context.Context, arg SaveBenefitStepParams) (int64, error)
	SaveCapitalAssetStep(ctx context.Context, arg SaveCapitalAssetStepParams) (int64, error)
	SaveDistributionStep(ctx context.Context, arg SaveDistributionStepParams) (int64, error)
	SaveFundingSourceStep(ctx context.Context, arg SaveFundingSourceStepParams) (int64, error)
	SaveInventoryPurchaseStep(ctx context.Context, arg SaveInventoryPurchaseStepParams) (int64, error)
	SaveOperatingExpenseStep(ctx context.Context, arg SaveOperatingExpenseStepParams) (int64, error)
	SavePayrollTaxRatesStep(ctx context.Context, arg SavePayrollTaxRatesStepParams) error
	SavePlan(ctx context.Context, arg SavePlanParams) error
	SaveProductStep(ctx context.Context, arg SaveProductStepParams) (int64, error)
	SaveSalaryRoleStep(ctx context.Context, arg SaveSalaryRoleStepParams) (int64, error)
	SaveSalesGrowthCurveStep(ctx context.Context, arg SaveSalesGrowthCurveStepParams) error
	SaveSession(ctx context.Context, arg SaveSessionParams) error
	SaveStartingBalancesStep(ctx context.Context, arg SaveStartingBalancesStepParams) error
	SaveStartupCostStep(ctx context.Context, arg SaveStartupCostStepParams) (int64, error)
	SoftDeleteBenefitsByPlan(ctx context.Context, arg SoftDeleteBenefitsByPlanParams) error
	SoftDeleteCapitalAssetsByPlan(ctx context.Context, arg SoftDeleteCapitalAssetsByPlanParams) error
	SoftDeleteDistributionsByPlan(ctx context.Context, arg SoftDeleteDistributionsByPlanParams) error
	SoftDeleteFundingSourcesByPlan(ctx context.Context, arg SoftDeleteFundingSourcesByPlanParams) error
	SoftDeleteInventoryPurchasesByPlan(ctx context.Context, arg SoftDeleteInventoryPurchasesByPlanParams) error
	SoftDeleteOperatingExpensesByPlan(ctx context.Context, arg SoftDeleteOperatingExpensesByPlanParams) error
	SoftDeletePlan(ctx context.Context, arg SoftDeletePlanParams) (int64, error)
	SoftDeleteProductsByPlan(ctx context.Context, arg SoftDeleteProductsByPlanParams) error
	SoftDeleteSalaryRolesByPlan(ctx context.Context, arg SoftDeleteSalaryRolesByPlanParams) error
	SoftDeleteStartupCostsByPlan(ctx context.Context, arg SoftDeleteStartupCostsByPlanParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error)
	UpdateInviteStatus(ctx context.Context, arg UpdateInviteStatusParams) (int64, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpsertUserCredentials(ctx context.Context, arg UpsertUserCredentialsParams) error
	UpsertWizardSection(ctx context.Context, arg UpsertWizardSectionParams) error
}

var _ Querier = (*Queries)(nil)
