// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: salary_role.sql

package db

import (
	"context"
	"database/sql"
)

const createSalaryRoleDraft = `-- name: CreateSalaryRoleDraft :exec
INSERT INTO salary_roles (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateSalaryRoleDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSalaryRoleDraft(ctx context.Context, arg CreateSalaryRoleDraftParams) error {
	_, err := q.db.ExecContext(ctx, createSalaryRoleDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSalaryRole = `-- name: DeleteSalaryRole :execrows
UPDATE salary_roles SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteSalaryRoleParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteSalaryRole(ctx context.Context, arg DeleteSalaryRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSalaryRole, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findSalaryRoleDraft = `-- name: FindSalaryRoleDraft :one
SELECT id, role, is_contractor, headcount, monthly_pay, growth_yr2, growth_yr3, status, current_step
FROM salary_roles
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindSalaryRoleDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindSalaryRoleDraftRow struct {
	ID           string  `db:"id" json:"id"`
	Role         string  `db:"role" json:"role"`
	IsContractor int64   `db:"is_contractor" json:"is_contractor"`
	Headcount    int64   `db:"headcount" json:"headcount"`
	MonthlyPay   int64   `db:"monthly_pay" json:"monthly_pay"`
	GrowthYr2    float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3    float64 `db:"growth_yr3" json:"growth_yr3"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) FindSalaryRoleDraft(ctx context.Context, arg FindSalaryRoleDraftParams) (FindSalaryRoleDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findSalaryRoleDraft, arg.PlanID, arg.Status)
	var i FindSalaryRoleDraftRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.IsContractor,
		&i.Headcount,
		&i.MonthlyPay,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getSalaryRole = `-- name: GetSalaryRole :one
SELECT id, role, is_contractor, headcount, monthly_pay, growth_yr2, growth_yr3, status, current_step
FROM salary_roles
WHERE id = ? AND deleted_at IS NULL
`

type GetSalaryRoleRow struct {
	ID           string  `db:"id" json:"id"`
	Role         string  `db:"role" json:"role"`
	IsContractor int64   `db:"is_contractor" json:"is_contractor"`
	Headcount    int64   `db:"headcount" json:"headcount"`
	MonthlyPay   int64   `db:"monthly_pay" json:"monthly_pay"`
	GrowthYr2    float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3    float64 `db:"growth_yr3" json:"growth_yr3"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetSalaryRole(ctx context.Context, id string) (GetSalaryRoleRow, error) {
	row := q.db.QueryRowContext(ctx, getSalaryRole, id)
	var i GetSalaryRoleRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.IsContractor,
		&i.Headcount,
		&i.MonthlyPay,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteSalaryRoles = `-- name: ListCompleteSalaryRoles :many
SELECT id, role, is_contractor, headcount, monthly_pay, growth_yr2, growth_yr3, status, current_step
FROM salary_roles
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteSalaryRolesParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteSalaryRolesRow struct {
	ID           string  `db:"id" json:"id"`
	Role         string  `db:"role" json:"role"`
	IsContractor int64   `db:"is_contractor" json:"is_contractor"`
	Headcount    int64   `db:"headcount" json:"headcount"`
	MonthlyPay   int64   `db:"monthly_pay" json:"monthly_pay"`
	GrowthYr2    float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3    float64 `db:"growth_yr3" json:"growth_yr3"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteSalaryRoles(ctx context.Context, arg ListCompleteSalaryRolesParams) ([]ListCompleteSalaryRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteSalaryRoles, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteSalaryRolesRow{}
	for rows.Next() {
		var i ListCompleteSalaryRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.IsContractor,
			&i.Headcount,
			&i.MonthlyPay,
			&i.GrowthYr2,
			&i.GrowthYr3,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSalaryRoleSortOrder = `-- name: MaxSalaryRoleSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM salary_roles WHERE plan_id = ?
`

func (q *Queries) MaxSalaryRoleSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxSalaryRoleSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveSalaryRoleStep = `-- name: SaveSalaryRoleStep :execrows
UPDATE salary_roles
SET role = ?, is_contractor = ?, headcount = ?, monthly_pay = ?, growth_yr2 = ?, growth_yr3 = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveSalaryRoleStepParams struct {
	Role         string  `db:"role" json:"role"`
	IsContractor int64   `db:"is_contractor" json:"is_contractor"`
	Headcount    int64   `db:"headcount" json:"headcount"`
	MonthlyPay   int64   `db:"monthly_pay" json:"monthly_pay"`
	GrowthYr2    float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3    float64 `db:"growth_yr3" json:"growth_yr3"`
	Status       string  `db:"status" json:"status"`
	CurrentStep  int64   `db:"current_step" json:"current_step"`
	UpdatedAt    int64   `db:"updated_at" json:"updated_at"`
	ID           string  `db:"id" json:"id"`
}

func (q *Queries) SaveSalaryRoleStep(ctx context.Context, arg SaveSalaryRoleStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveSalaryRoleStep,
		arg.Role,
		arg.IsContractor,
		arg.Headcount,
		arg.MonthlyPay,
		arg.GrowthYr2,
		arg.GrowthYr3,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
