// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_growth_curve.sql

package db

import (
	"context"
)

const getSalesGrowthCurveRow = `-- name: GetSalesGrowthCurveRow :one
SELECT y1_q1, y1_q2, y1_q3, y1_q4, growth_yr2, growth_yr3, current_step
FROM sales_growth_curve WHERE plan_id = ?
`

type GetSalesGrowthCurveRowRow struct {
	Y1Q1        float64 `db:"y1_q1" json:"y1_q1"`
	Y1Q2        float64 `db:"y1_q2" json:"y1_q2"`
	Y1Q3        float64 `db:"y1_q3" json:"y1_q3"`
	Y1Q4        float64 `db:"y1_q4" json:"y1_q4"`
	GrowthYr2   float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3   float64 `db:"growth_yr3" json:"growth_yr3"`
	CurrentStep int64   `db:"current_step" json:"current_step"`
}

func (q *Queries) GetSalesGrowthCurveRow(ctx context.Context, planID string) (GetSalesGrowthCurveRowRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesGrowthCurveRow, planID)
	var i GetSalesGrowthCurveRowRow
	err := row.Scan(
		&i.Y1Q1,
		&i.Y1Q2,
		&i.Y1Q3,
		&i.Y1Q4,
		&i.GrowthYr2,
		&i.GrowthYr3,
		&i.CurrentStep,
	)
	return i, err
}

const saveSalesGrowthCurveStep = `-- name: SaveSalesGrowthCurveStep :exec
INSERT INTO sales_growth_curve (plan_id, y1_q1, y1_q2, y1_q3, y1_q4, growth_yr2, growth_yr3, current_step, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plan_id) DO UPDATE SET
	y1_q1 = excluded.y1_q1,
	y1_q2 = excluded.y1_q2,
	y1_q3 = excluded.y1_q3,
	y1_q4 = excluded.y1_q4,
	growth_yr2 = excluded.growth_yr2,
	growth_yr3 = excluded.growth_yr3,
	current_step = excluded.current_step,
	updated_at = excluded.updated_at
`

type SaveSalesGrowthCurveStepParams struct {
	PlanID      string  `db:"plan_id" json:"plan_id"`
	Y1Q1        float64 `db:"y1_q1" json:"y1_q1"`
	Y1Q2        float64 `db:"y1_q2" json:"y1_q2"`
	Y1Q3        float64 `db:"y1_q3" json:"y1_q3"`
	Y1Q4        float64 `db:"y1_q4" json:"y1_q4"`
	GrowthYr2   float64 `db:"growth_yr2" json:"growth_yr2"`
	GrowthYr3   float64 `db:"growth_yr3" json:"growth_yr3"`
	CurrentStep int64   `db:"current_step" json:"current_step"`
	CreatedAt   int64   `db:"created_at" json:"created_at"`
	UpdatedAt   int64   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SaveSalesGrowthCurveStep(ctx context.Context, arg SaveSalesGrowthCurveStepParams) error {
	_, err := q.db.ExecContext(ctx, saveSalesGrowthCurveStep,
		arg.PlanID,
		arg.Y1Q1,
		arg.Y1Q2,
		arg.Y1Q3,
		arg.Y1Q4,
		arg.GrowthYr2,
		arg.GrowthYr3,
		arg.CurrentStep,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
