// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: startup_cost.sql

package db

import (
	"context"
	"database/sql"
)

const createStartupCostDraft = `-- name: CreateStartupCostDraft :exec
INSERT INTO startup_costs (id, plan_id, status, current_step, sort_order, created_at, updated_at)
VALUES (?, ?, ?, 0, ?, ?, ?)
`

type CreateStartupCostDraftParams struct {
	ID        string `db:"id" json:"id"`
	PlanID    string `db:"plan_id" json:"plan_id"`
	Status    string `db:"status" json:"status"`
	SortOrder int64  `db:"sort_order" json:"sort_order"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	UpdatedAt int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateStartupCostDraft(ctx context.Context, arg CreateStartupCostDraftParams) error {
	_, err := q.db.ExecContext(ctx, createStartupCostDraft,
		arg.ID,
		arg.PlanID,
		arg.Status,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteStartupCost = `-- name: DeleteStartupCost :execrows
UPDATE startup_costs SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type DeleteStartupCostParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) DeleteStartupCost(ctx context.Context, arg DeleteStartupCostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStartupCost, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findStartupCostDraft = `-- name: FindStartupCostDraft :one
SELECT id, name, amount, status, current_step
FROM startup_costs
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
LIMIT 1
`

type FindStartupCostDraftParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type FindStartupCostDraftRow struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Amount      int64  `db:"amount" json:"amount"`
	Status      string `db:"status" json:"status"`
	CurrentStep int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) FindStartupCostDraft(ctx context.Context, arg FindStartupCostDraftParams) (FindStartupCostDraftRow, error) {
	row := q.db.QueryRowContext(ctx, findStartupCostDraft, arg.PlanID, arg.Status)
	var i FindStartupCostDraftRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const getStartupCost = `-- name: GetStartupCost :one
SELECT id, name, amount, status, current_step
FROM startup_costs
WHERE id = ? AND deleted_at IS NULL
`

type GetStartupCostRow struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Amount      int64  `db:"amount" json:"amount"`
	Status      string `db:"status" json:"status"`
	CurrentStep int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) GetStartupCost(ctx context.Context, id string) (GetStartupCostRow, error) {
	row := q.db.QueryRowContext(ctx, getStartupCost, id)
	var i GetStartupCostRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Status,
		&i.CurrentStep,
	)
	return i, err
}

const listCompleteStartupCosts = `-- name: ListCompleteStartupCosts :many
SELECT id, name, amount, status, current_step
FROM startup_costs
WHERE plan_id = ? AND status = ? AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListCompleteStartupCostsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Status string `db:"status" json:"status"`
}

type ListCompleteStartupCostsRow struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Amount      int64  `db:"amount" json:"amount"`
	Status      string `db:"status" json:"status"`
	CurrentStep int64  `db:"current_step" json:"current_step"`
}

func (q *Queries) ListCompleteStartupCosts(ctx context.Context, arg ListCompleteStartupCostsParams) ([]ListCompleteStartupCostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompleteStartupCosts, arg.PlanID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompleteStartupCostsRow{}
	for rows.Next() {
		var i ListCompleteStartupCostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Status,
			&i.CurrentStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxStartupCostSortOrder = `-- name: MaxStartupCostSortOrder :one
SELECT COALESCE(MAX(sort_order), -1) + 1 FROM startup_costs WHERE plan_id = ?
`

func (q *Queries) MaxStartupCostSortOrder(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxStartupCostSortOrder, planID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveStartupCostStep = `-- name: SaveStartupCostStep :execrows
UPDATE startup_costs
SET name = ?, amount = ?, status = ?, current_step = ?, updated_at = ?
WHERE id = ?
`

type SaveStartupCostStepParams struct {
	Name        string `db:"name" json:"name"`
	Amount      int64  `db:"amount" json:"amount"`
	Status      string `db:"status" json:"status"`
	CurrentStep int64  `db:"current_step" json:"current_step"`
	UpdatedAt   int64  `db:"updated_at" json:"updated_at"`
	ID          string `db:"id" json:"id"`
}

func (q *Queries) SaveStartupCostStep(ctx context.Context, arg SaveStartupCostStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveStartupCostStep,
		arg.Name,
		arg.Amount,
		arg.Status,
		arg.CurrentStep,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
