// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: starting_balances.sql

package db

import (
	"context"
)

const getStartingBalancesRow = `-- name: GetStartingBalancesRow :one
SELECT cash, accounts_receivable, prepaid_expenses, accounts_payable, accrued_expenses, current_step
FROM starting_balances WHERE plan_id = ?
`

type GetStartingBalancesRowRow struct {
	Cash               int64 `db:"cash" json:"cash"`
	AccountsReceivable int64 `db:"accounts_receivable" json:"accounts_receivable"`
	PrepaidExpenses    int64 `db:"prepaid_expenses" json:"prepaid_expenses"`
	AccountsPayable    int64 `db:"accounts_payable" json:"accounts_payable"`
	AccruedExpenses    int64 `db:"accrued_expenses" json:"accrued_expenses"`
	CurrentStep        int64 `db:"current_step" json:"current_step"`
}

func (q *Queries) GetStartingBalancesRow(ctx context.Context, planID string) (GetStartingBalancesRowRow, error) {
	row := q.db.QueryRowContext(ctx, getStartingBalancesRow, planID)
	var i GetStartingBalancesRowRow
	err := row.Scan(
		&i.Cash,
		&i.AccountsReceivable,
		&i.PrepaidExpenses,
		&i.AccountsPayable,
		&i.AccruedExpenses,
		&i.CurrentStep,
	)
	return i, err
}

const saveStartingBalancesStep = `-- name: SaveStartingBalancesStep :exec
INSERT INTO starting_balances (plan_id, cash, accounts_receivable, prepaid_expenses, accounts_payable, accrued_expenses, current_step, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plan_id) DO UPDATE SET
	cash = excluded.cash,
	accounts_receivable = excluded.accounts_receivable,
	prepaid_expenses = excluded.prepaid_expenses,
	accounts_payable = excluded.accounts_payable,
	accrued_expenses = excluded.accrued_expenses,
	current_step = excluded.current_step,
	updated_at = excluded.updated_at
`

type SaveStartingBalancesStepParams struct {
	PlanID             string `db:"plan_id" json:"plan_id"`
	Cash               int64  `db:"cash" json:"cash"`
	AccountsReceivable int64  `db:"accounts_receivable" json:"accounts_receivable"`
	PrepaidExpenses    int64  `db:"prepaid_expenses" json:"prepaid_expenses"`
	AccountsPayable    int64  `db:"accounts_payable" json:"accounts_payable"`
	AccruedExpenses    int64  `db:"accrued_expenses" json:"accrued_expenses"`
	CurrentStep        int64  `db:"current_step" json:"current_step"`
	CreatedAt          int64  `db:"created_at" json:"created_at"`
	UpdatedAt          int64  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SaveStartingBalancesStep(ctx context.Context, arg SaveStartingBalancesStepParams) error {
	_, err := q.db.ExecContext(ctx, saveStartingBalancesStep,
		arg.PlanID,
		arg.Cash,
		arg.AccountsReceivable,
		arg.PrepaidExpenses,
		arg.AccountsPayable,
		arg.AccruedExpenses,
		arg.CurrentStep,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
