// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT OR IGNORE INTO users (id, email, first_name, last_name, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string `db:"id" json:"id"`
	Email     string `db:"email" json:"email"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
	)
	return err
}

const deletePlanAccessByUser = `-- name: DeletePlanAccessByUser :exec
DELETE FROM plan_access WHERE user_id = ?
`

func (q *Queries) DeletePlanAccessByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePlanAccessByUser, userID)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUser, userID)
	return err
}

const deleteUserCredentialsByEmail = `-- name: DeleteUserCredentialsByEmail :exec
DELETE FROM users_credentials WHERE email = ?
`

func (q *Queries) DeleteUserCredentialsByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCredentialsByEmail, email)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT email, first_name, last_name FROM users WHERE id = ? AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	Email     string `db:"email" json:"email"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.Email, &i.FirstName, &i.LastName)
	return i, err
}

const getUserCredentialsByEmail = `-- name: GetUserCredentialsByEmail :one
SELECT u.id, uc.password_hash
FROM users u
JOIN users_credentials uc ON u.email = uc.email
WHERE LOWER(u.email) = ? AND u.deleted_at IS NULL
`

type GetUserCredentialsByEmailRow struct {
	ID           string `db:"id" json:"id"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserCredentialsByEmail(ctx context.Context, email string) (GetUserCredentialsByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentialsByEmail, email)
	var i GetUserCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id FROM users WHERE LOWER(email) = ? AND deleted_at IS NULL
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	DeletedAt sql.NullInt64 `db:"deleted_at" json:"deleted_at"`
	ID        string        `db:"id" json:"id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteUser, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET first_name = ?, last_name = ? WHERE id = ?
`

type UpdateUserNameParams struct {
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserName, arg.FirstName, arg.LastName, arg.ID)
	return err
}

const upsertUserCredentials = `-- name: UpsertUserCredentials :exec
INSERT OR REPLACE INTO users_credentials (email, password_hash, created_at) VALUES (?, ?, ?)
`

type UpsertUserCredentialsParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	CreatedAt    int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertUserCredentials(ctx context.Context, arg UpsertUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserCredentials, arg.Email, arg.PasswordHash, arg.CreatedAt)
	return err
}
