// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wizard_progress.sql

package db

import (
	"context"
	"database/sql"
)

const listWizardSections = `-- name: ListWizardSections :many
SELECT section, completed_at FROM wizard_sections WHERE plan_id = ? AND hub = ?
`

type ListWizardSectionsParams struct {
	PlanID string `db:"plan_id" json:"plan_id"`
	Hub    string `db:"hub" json:"hub"`
}

type ListWizardSectionsRow struct {
	Section     string        `db:"section" json:"section"`
	CompletedAt sql.NullInt64 `db:"completed_at" json:"completed_at"`
}

func (q *Queries) ListWizardSections(ctx context.Context, arg ListWizardSectionsParams) ([]ListWizardSectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWizardSections, arg.PlanID, arg.Hub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWizardSectionsRow{}
	for rows.Next() {
		var i ListWizardSectionsRow
		if err := rows.Scan(&i.Section, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWizardSection = `-- name: UpsertWizardSection :exec
INSERT INTO wizard_sections (plan_id, hub, section, completed_at) VALUES (?, ?, ?, ?)
ON CONFLICT(plan_id, hub, section) DO UPDATE SET completed_at = excluded.completed_at
`

type UpsertWizardSectionParams struct {
	PlanID      string        `db:"plan_id" json:"plan_id"`
	Hub         string        `db:"hub" json:"hub"`
	Section     string        `db:"section" json:"section"`
	CompletedAt sql.NullInt64 `db:"completed_at" json:"completed_at"`
}

func (q *Queries) UpsertWizardSection(ctx context.Context, arg UpsertWizardSectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertWizardSection,
		arg.PlanID,
		arg.Hub,
		arg.Section,
		arg.CompletedAt,
	)
	return err
}
